### PR TITLE
fix bug with expires_at timestamp parsing.

### PR DESCRIPTION
**Pull request by dobon**

### CODE REVIEW

**Comment by dobon** [comment]
@pboling Is there any way that I can increase the visibility of this PR? I would really like for this to be merged. The current behavior is 100% bugged.

**Review by pboling — APPROVED** [review]
LGTM

**Comment by pboling** [comment]
Thanks for the ping @dobon !

**Comment by dobon** [comment]
@pboling Thanks! What is the procedure for getting this merged down to 1-4-stable branch?

**Comment by pboling** [comment]
@dobon 1.4.7 is released with this fix.

**Comment by dobon** [comment]
@pboling Thank you very much! Much appreciated!

**Pull request merged**
