### PR TITLE
Use Base64.strict_encode64

### PR DESCRIPTION
**Pull request by meganemura**
This is a successor of #325.

### CODE REVIEW

**Comment by meganemura** [comment]
@josephpage @pboling Would you please review this?

**Comment by pboling** [comment]
I need to review this for breaking changes.

We are not dropping any existing support for old Rubies in the 2.0.0 release.

```
# Base64.strict_encode64 is not available on Ruby 1.8.7
```

This might need to go into the follow up 3.0.0 release.

**Comment by meganemura** [comment]
@pboling 

In https://github.com/oauth-xx/oauth2/milestone/1 and #325, 

> 2.x is the last version series that will have Ruby 1.9/2.0/2.1/2.2 support.

So, I think 2.x release does not need to support ruby 1.8.

**Comment by pboling** [comment]
Oh good point!  I need to add a Ruby support matrix to the Readme.

**Pull request merged**
