### PR TITLE
Allows passing extra headers to the Client Credentials strategy

### PR DESCRIPTION
**Pull request by nikz**
Hiya,

This fixes (what I think) is a wee bug with the `client_credentials` grant where it won't allow passing through extra headers to the token request.

It includes a passing spec, although I'll be the first to admit it's a little hacky... any guidance there appreciated.

I also didn't add any documentation since it's a bugfix, and there's language to that effect under [Authorization Grants](https://github.com/intridea/oauth2#authorization-grants) but happy to do that if you'd like.

Cheers!

Nik

### CODE REVIEW

**Comment by thedarkside** [comment]
I ran into the same issue. It *is* a bug!

**Comment by djberg96** [comment]
Seems like this ought to be merged. The failures appear to be JRuby and/or Ruby 1.9.x or earlier only.

**Comment by josephpage** [comment]
Hey @nikz,
The gem now has a new team of maintainers. 🎉 
I'll be happy to merge your PR when the conflits will be resolved.

**Comment by nikz** [comment]
@josephpage Great! I thought I made the change just now, but it seems Github isn't happy with it so I might have to do it properly instead - give me some time and I'll get it fixed up for you.

**Comment by pboling** [comment]
You will need to rebase on latest master in order to resolve the conflicts.

**Comment by nikz** [comment]
@pboling @josephpage I actually think this has been fixed by [this change](https://github.com/oauth-xx/oauth2/commit/fc0735f7c46e8fd9f5817b2fbc5091d5abf421b6). We could include the spec to verify it doesn't break again if you'd like (happy to adjust the PR), or feel free to close this PR. 

Thanks!

**Comment by pboling** [comment]
@nikz Yes, great idea.  More specs is great!  I will extract the spec and merge it, unless a wild PR appears before I get to it. ;)

**Comment by nikz** [comment]
@pboling sent up #381 for you, so I'll close this one up now. Cheers!

**Pull request closed without merging**
