### PR TITLE
Allow use faraday 1.0

### PR DESCRIPTION
**Pull request by Fudoshiki**

### CODE REVIEW

**Comment by etiennebarrie** [comment]
Would it be possible to release a 1.x version (i.e. `v1.4.2`) with this included? I don't think we need the rest of the changes from 2.0 to be able to loosen that constraint.

**Comment by pboling** [comment]
Just need a PR to https://github.com/oauth-xx/oauth2/tree/1-4-stable, that's why we made the branch!  My fear is that it would be horribly broken... but let's find out.

**Comment by etiennebarrie** [comment]
I just saw v1.4.2, that's awesome. Thank you very much!

**Comment by pboling** [comment]
It was broken, just in the specs, but I fixed it all up!

CC @Fudoshiki

**Pull request merged**
