### PR TITLE
Updates from upstream pull requests

### PR DESCRIPTION
**Pull request by spectator**

### CODE REVIEW

**Comment by spectator** [comment]
🤦‍♂️ sorry, created against wrong repo

**Comment by pboling** [comment]
We like updates too! @spectator ;)

**Comment by spectator** [comment]
hey @pboling ! are you the new maintainer? it still looks abandoned... I only combined a few existing pull requests into one, happy to help with those

**Comment by spectator** [comment]
If you are interested, here is the PR I'm finishing up for our fork https://github.com/PeerStreet/oauth2/pull/1 it includes two pull requests I found specifically useful for us as well as a few fixes for issues I run into. I'll be more than happy to resubmit it here.

**Comment by pboling** [comment]
Yes, I am the new maintainer.  We are working on getting the gem back in shape.  I don't yet have push access to RubyGems.org, but I hope to soon.  All help is appreciated.  I am monitoring comments, but haven't had time to go through the issue and PR backlogs yet.

**Comment by spectator** [comment]
Awesome! Thank you for takin on this responsibility! 🙇 

I'm always happy to help when I can. I'll send one fix I made last night and if you have anything specific you'd like somebody else to look into then let me know.

There is a few PRs you might look into first

https://github.com/oauth-xx/oauth2/pull/328
Very minor, basically no brainer and it is from Akira ❤️ 

https://github.com/oauth-xx/oauth2/pull/326
This one has good fixes too
* it appears to handle gem and platform dependencies better (fair amount of complains on that in issues and PRs)
* good fixes to tests, CI and addressing rubocop complains

**Pull request closed without merging**
