### PR TITLE
Upgraded to Faraday 2.0 and Ruby 3.1.0

### PR DESCRIPTION
**Pull request by prasanna**
Upgraded Faraday to 2.0 since I already depend on it and don't want to downgrade.

### CODE REVIEW

**Comment by jrochkind** [comment]
No code changes but in specs?  Assuming all tests pass... what about making the gemspec allow Faraday 1.x or 2.x both, to make it easier for mixed dependency trees?

(i am not a maintainer, just a peer with an opinion. I don't know if the maintainer(s) are still active).

**Comment by jrochkind** [comment]
```
spec.add_dependency 'faraday', ['>= 1.0', '< 3.0']
```

Or, as prior to this commit all the way back to 0.8 was allowed:

```
spec.add_dependency 'faraday', ['>= 0.8', '< 3.0']
```

**Comment by pboling** [comment]
I would be very surprised if it *actually* worked with all those versions of Faraday... IIRC the Faraday API has changed significantly.  But if it works it works, and if it doesn't we can disable the broken versions.

**Comment by pboling** [comment]
I approved the spec run, and this breaks a lot of stuff in the build (which is why we held off on doing it).  Will require some investigation.

**Comment by pboling** [comment]
I tried to cleanup with changes from latest master, but still failing badly...

**Comment by pboling** [comment]
I am doing my best to actively maintain this gem... I will definitely pay attention and review anything and all pull requests submitted.

If we can't support for Faraday 1 and 2, then we will have to keep the version 2 support for the version 2.0 release of the gem (meaning the PR should be against master only).  Since it would be a breaking change we'd have to major bump the version anyways.

Another suggestion elsewhere was to just remove Faraday entirely, and that may also be feasible... :/

**Comment by jrochkind** [comment]
Cool. 

Just to verify -- this branch fails lots of tests even if you run with faraday 1.9.3.  The same tests as with faraday 2.x. 

@prasanna, I think the other changes you included in this branch are maybe not right? Can you say anything about what motivated the code changes you committed here?

I will see if I can find some more time to work on this, starting fresh from master branch.

**Comment by jrochkind** [comment]
Wait a second... the master branch already allows faraday 2.0 and is already passing! @pboling already took care of it?!?

Thank you @pboling!

I guess this branch is just about ruby 3.1.0 support now?  Or something? That is not my own current priority, I just cared about faraday 2.0! 

Which looks like is already taken care of on master... via #561.  Awesome!  Just needs a release. OK, you've done what I needed!

**Comment by pboling** [comment]
Yeah `master` is the 96% complete version `oauth2` version 2.0.0 release candidate.  Ideally people would start using master.  Checkout the Changelog, as there *are* breaking changes, though mostly minor.  I would love to have some help figuring out how to get v2 over the finish line (see milestone)!

**Comment by jrochkind** [comment]
Oh boy, master is for v2?  OK, once it *does* get released... I'm going to have to go the several gems I depend on that depend on oauth2, and get them to upgrade to oauth2 v2 if I want to use faraday 2.... the struggle continues. 

Is there any hope of releasing an oauth2 1.x release that allows faraday 2.x? If someone else helped with PR?

**Comment by pboling** [comment]
> Is there any hope of releasing an oauth2 1.x release that allows faraday 2.x? If someone else helped with PR?

Definitely... *but* it would have to be support for the current old Faraday as well.  If we drop support for old Faraday it must be a major version bump.  So, if you can help do the magic that lets us support both on the 1.x line, then we all win.

Note that the work would need to be done against the [`1-4-stable` branch](https://github.com/oauth-xx/oauth2/tree/1-4-stable).  It and `master` have diverged significantly.

**Comment by pboling** [comment]
closing this PR, since we're already on Faraday 2 on the master branch

**Comment by pboling** [comment]
I've dropped all rubies prior to 2.5 from the build on master.  This won't help with the `1-4-stable` work, but we definitely don't need to continue with the old ruby support for the v2 release.

**Comment by jrochkind** [comment]
@pboling Thanks! Current master gemspec already says it does support faraday 1.x as well as faraday 2.x.

https://github.com/oauth-xx/oauth2/blob/4d79264d5aa40b70f98419eafa382648f1df4e61/oauth2.gemspec#L9

 Is that an error? If not, there is no extra work to backporting with support for faraday 1.x as well as 2.x, right?

**Comment by jrochkind** [comment]
(It also occurs to me I'm going to have the same headache with oauth2 by the way. My apps have only indirect dependency on oauth 2 -- they depend on gems that depend on oauth2, and sometimes multiple gems that each depend on oauth2. Unless these intermediate dependencies can support both oauth2 v1 and v2 ... I won't be able to upgrade any of them to a version that supports oauth2 2.0 until I can upgrade *all* of them to a version that does. The same problem I've been having with faraday, that brought me here. :(  So it might be a while until my apps are using oauth2 v2.0)

**Comment by pboling** [comment]
@jrochkind A few things:

`master` branch is effectively currently oauth2 v2.0.  It is so tantalizingly close to a release.
`master` branch (oauth v2.0) does support Faraday v1 and v2, so you should be able to use that to upgrade all the things (taking care about the few breaking changes).

---

`1-4-stable` branch does not support Faraday v2.0, and getting it to do so might be difficult.  I honestly have no idea.  Might be splendidly easy.  If you want a 1.x release that supports Faraday v1 *and* v2, then you'll need to submit a pull request.

It sounds like this is a worthwhile effort as it may ease the upgrade path for people.

**Pull request closed without merging**
