### PR TITLE
Fix missing custom headers in get_token

### PR DESCRIPTION
**Pull request by anvox**
I propose this way to quickly get over #498 
If we use `HashWithIndifferentAccess` or anything similar, we must revise and change whole system inputs, outputs. Currently, system returns hashes with mixed keys in string and symbol. 
This change looks like a patch but it has 2 pros besides fixing issue. 

- Simple implement, we needn't add complex things like HashWithIndifferentAccess
- Keep others interfaces same. 

After, we could have a bigger implement to standardize inputs, outputs.

### CODE REVIEW

**Comment by anvox** [comment]
@pboling  @antonlitvinenko  what do you think?

**Comment by pboling** [comment]
This looks good.  This bug is in the current release also, so we'll need another PR to get this same code into `1-4-stable`.  Can you do that as well @anvox ?  I think the simplest may be to squash merge this PR, and then take that squash merged commit SHA and cherry pick it into a branch off of `1-4-stable` for a new PR.

Going to squash merge this into master now.

**Comment by antonlitvinenko** [comment]
@anvox awesome! Thank you very much!

**Comment by anvox** [comment]
Thanks. PR to 1-4-stable https://github.com/oauth-xx/oauth2/pull/513 
I'll merge after all tests green.

**Pull request merged**
