### PR TITLE
Clean Changelog for 2.0.0 Release

### PR DESCRIPTION
**Pull request by josephpage**
Merges both PR #311 #295 into one PR and add some details.
Also allows deletion of this outdated wiki page : https://github.com/oauth-xx/oauth2/wiki/Changelog

### CODE REVIEW

**Comment by josephpage** [comment]
I'll update this PR until the [1.5.0 release](https://github.com/oauth-xx/oauth2/milestone/1).

**Comment by pboling** [comment]
@xtagon I have updated the milestone.  Now 2.0.0 retains Ruby 1.9/2.0/2.1 compatibility, but includes other breaking changes.

We will then release 3.0.0 to drop those old Ruby.

**Comment by xtagon** [comment]
Seems very sensible to me. Tons of people use this gem and I'm sure they'll appreciate not having surprises. 👍

**Comment by pboling** [comment]
We need to merge this so that further PRs can modify the change log according to the localized changes in each PR.

**Pull request merged**
