### PR TITLE
Add new token_method post_with_query_string

### PR DESCRIPTION
**Pull request by JCotton1123**
Hi, curious if you would accept a change like this? I'm working with a couple APIs where the token HTTP method must be a POST but the parameters must be passed via the query string.

### CODE REVIEW

**Review by utkarsh2102 — COMMENTED** [review]
Nice!
Could you also add tests?

**Comment by JCotton1123** [comment]
@utkarsh2102 added a test...let me know if this is sufficient or what else you might like to see. Thx

**Review by utkarsh2102 — APPROVED** [review]
This looks like a good feature to have! 🌮

**Comment by JCotton1123** [comment]
Hi, just checking in to see if this is mergable...

**Review by pboling — APPROVED** [review]
LGTM

**Comment by pboling** [comment]
Thanks @utkarsh2102 and @JCotton1123 !

**Comment by pboling** [comment]
(New) Maintainers are now discussing a new release of oauth.  It's been 3 years, so we have a bit of prep work to do.  Please lend a hand if you have some time!

**Comment by utkarsh2102** [comment]
That's awesome! How can I help?

**Pull request merged**
