### PR TITLE
Set basic_auth as default

### LINKED ISSUE #285: Version 1.3.0 has a breaking change
My code works fine in version 1.2.0, but in 1.3.0, the server I want to connect return the following error.
```
/home/shenghan/.rvm/gems/ruby-2.4.0/gems/oauth2-1.3.0/lib/oauth2/client.rb:119:in `request': unauthorized: Full authentication is required to access this resource (OAuth2::Error)
{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}
	from /home/shenghang/.rvm/gems/ruby-2.4.0/gems/oauth2-1.3.0/lib/oauth2/client.rb:146:in `get_token'
	from /home/shenghang/.rvm/gems/ruby-2.4.0/gems/oauth2-1.3.0/lib/oauth2/strategy/client_credentials.rb:20:in `get_token'
```
Here is the options we are using to connect.

```ruby
options = {
      :site               => 'https://nvidia.jamacloud.com',
      :context_path       => '',
      :token_url          => '/rest/oauth/token',
      :rest_base_path     => '/rest/latest',
      :ssl_verify_mode    => OpenSSL::SSL::VERIFY_PEER,
      :use_ssl            => true,
      :auth_type          => :oauth,
      :client_id          => clientId,
      :client_secret      => clientSecret,
      :http_debug         => debug
 }
```

### PR DESCRIPTION
**Pull request by tetsuya**
This PR fixes #285 by setting `:basic_auth` as default for `:auth_scheme`

### CODE REVIEW

**Comment by djberg96** [comment]
👍

**Comment by jhmoore** [comment]
FWIW, this was a breaking change for us.  Was this intended to be a breaking change?

**Comment by pboling** [comment]
@jhmoore The upcoming release, 1.5.0, will have breaking changes.  We are working on getting everything documented and prepared for a release as soon as possible.  The fix should be just adding a bit of config, as here: https://github.com/mkdynamic/omniauth-facebook/pull/291

**Comment by xtagon** [comment]
@pboling In that case should we call it `2.0.0` based on SemVer's requirement of bumping the major version for breaking changes? https://github.com/oauth-xx/oauth2/issues/262

**Comment by pboling** [comment]
@xtagon excellent point, and absolutely.  We have backwards incompatible changes and we need to thoroughly document them and align the next release version number accordingly.  Looks like `2.0.0` it is.

**Pull request merged**
